                           # Purpose: To calculate the result of the symptoms using all the Permutations
import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

global Abdominal_Pain_var, Anemia_var, Diarrhea_var, Vomiting_var, Weight_Loss_var, Bmi_var


            # Variables FOR THE Rules FUZZY MODEL


ap=ctrl.Antecedent(np.arange(0,11,1),'ap')
an=ctrl.Antecedent(np.arange(0,11,1),'an')
da=ctrl.Antecedent(np.arange(0,11,1),'da')
vom=ctrl.Antecedent(np.arange(0,11,1),'vom')
wl=ctrl.Antecedent(np.arange(0,11,1),'wl')
bmi = ctrl.Antecedent(np.arange(0, 41, 1), 'bmi')
cd = ctrl.Consequent(np.arange(0, 101, 1), 'cd')
ap['Mild']=fuzz.trimf(ap.universe,[0,0,4])
ap['Mod']=fuzz.trimf(ap.universe,[1,5,9])
ap['Sev']=fuzz.trimf(ap.universe,[6,10,10])
an['Mild']=fuzz.trimf(an.universe,[0,0,4])
an['Mod']=fuzz.trimf(an.universe,[1,5,9])
an['Sev']=fuzz.trimf(an.universe,[6,10,10])
da['Mild']=fuzz.trimf(da.universe,[0,0,4])
da['Mod']=fuzz.trimf(da.universe,[1,5,9])
da['Sev']=fuzz.trimf(da.universe,[6,10,10])
vom['OnceWeek']=fuzz.trimf(vom.universe,[0,0,4])
vom['ThriceWeek']=fuzz.trimf(vom.universe,[1,5,9])
vom['Daily']=fuzz.trimf(vom.universe,[6,10,10])
wl['US']=fuzz.trimf(wl.universe,[0,0,4])
wl['UL']=fuzz.trimf(wl.universe,[2,10,10])
bmi['UW'] = fuzz.trimf(bmi.universe, [0,0,22])
bmi['Normal'] = fuzz.trimf(bmi.universe, [15,22,29])
bmi['OW'] = fuzz.trimf(bmi.universe, [22,40,40])
cd['NCD'] = fuzz.trimf(cd.universe, [0, 0, 1])
cd['EL'] = fuzz.trimf(cd.universe, [0, 10, 20])
cd['VVL'] = fuzz.trimf(cd.universe, [10,20,30])
cd['VL'] = fuzz.trimf(cd.universe, [20,30,40])
cd['L'] = fuzz.trimf(cd.universe, [30,40,50])
cd['ML'] = fuzz.trimf(cd.universe, [40,50,60])
cd['M'] = fuzz.trimf(cd.universe, [50,60,70])
cd['MH'] = fuzz.trimf(cd.universe, [60,70,80])
cd['H'] = fuzz.trimf(cd.universe, [70,80,90])
cd['VH'] = fuzz.trimf(cd.universe, [80,90,100])
cd['VVH'] = fuzz.trimf(cd.universe, [90,100,100])


            #  INPUT FUNCTION OF THE SYMPTOMS OF THE PATIENT


def Symptoms_input():
    global Abdominal_Pain_var, Anemia_var, Diarrhea_var, Vomiting_var, Weight_Loss_var, Bmi_var


    print("enter the Symtoms for the range of 0.0-10.0:::\n")
   
    Abdominal_Pain_var = float(input("Enter the Abdominal Pain (0.0-10.0):"))
    if(Abdominal_Pain_var<0.0 or Abdominal_Pain_var>10.0):
        print("Invalid input")
        Symptoms_input()
    Anemia_var = float(input("Enter the Anemia (0.0-10.0):"))
    if(Anemia_var<0.0 or Anemia_var>10.0):
        print("Invalid input")
        Symptoms_input()
    Diarrhea_var = float(input("Enter the Diarrhea (0.0-10.0):"))
    if(Diarrhea_var<0.0 or Diarrhea_var>10.0):
        print("Invalid input")
        Symptoms_input()
    Vomiting_var = float(input("Enter the Vomiting (0.0-10.0):"))
    if(Vomiting_var<0.0 or Vomiting_var>10.0):
        print("Invalid input")
        Symptoms_input()
    Weight_Loss_var = float(input("Enter the Weight Loss (0.0-10.0):"))
    if(Weight_Loss_var<0.0 or Weight_Loss_var>10.0):
        print("Invalid input")
        Symptoms_input()
    Bmi_var = float(input("Enter the Bmi (0.0-40.0):"))
    if(Bmi_var<0.0 or Bmi_var>40.0):
        print("Invalid input")
        Symptoms_input()



            # Function To calculate the result of the symptoms using all the Permutations


def Result(res):
    pass

def Calculate():
    # Check_Flag = Check()
    # if Check_Flag == 0:
        
        global Abdominal_Pain_var, Anemia_var, Diarrhea_var, Vomiting_var, Weight_Loss_var, Bmi_var

        BMI_value = str(Bmi_var)
        BMI_value = BMI_value.strip()
        BMI_value = BMI_value.replace(" ", "")
        BMI_value = float(BMI_value)
        
        Weight_Loss_value = str(Weight_Loss_var)
        Weight_Loss_value = Weight_Loss_value.strip()
        Weight_Loss_value = Weight_Loss_value.replace(" ", "")
        Weight_Loss_value = float(Weight_Loss_value)
   
        Vomiting_value = str(Vomiting_var)
        Vomiting_value = Vomiting_value.strip()
        Vomiting_value = Vomiting_value.replace(" ", "")
        Vomiting_value = float(Vomiting_value)
  
        Diarrhea_value = str(Diarrhea_var)
        Diarrhea_value = Diarrhea_value.strip()
        Diarrhea_value = Diarrhea_value.replace(" ", "")
        Diarrhea_value = float(Diarrhea_value)
   
        Anemia_value = str(Anemia_var)
        Anemia_value = Anemia_value.strip()
        Anemia_value = Anemia_value.replace(" ", "")
        Anemia_value = float(Anemia_value)

        Abdominal_Pain_value = str(Abdominal_Pain_var)
        Abdominal_Pain_value = Abdominal_Pain_value.strip()
        Abdominal_Pain_value = Abdominal_Pain_value.replace(" ", "")
        Abdominal_Pain_value = float(Abdominal_Pain_value)

        rule1 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['NCD'])
        rule2 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['NCD'])
        rule3 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['NCD'])
        rule4 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['NCD'])
        rule5 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['NCD'])
        rule6 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['NCD'])
        rule7 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['EL'])
        rule8 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'],cd['NCD'])
        rule9 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['EL'])
        rule10 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['VVL'])
        rule11 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'],cd['EL'])
        rule12 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['VVL'])
        rule13 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['VVL'])
        rule14 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['EL'])
        rule15 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['VVL'])
        rule16 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['VL'])
        rule17 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['VVL'])
        rule18 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['VL'])
        rule19 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['EL'])
        rule20 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['NCD'])
        rule21 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['EL'])
        rule22 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['VVL'])
        rule23 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['EL'])
        rule24 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['VVL'])
        rule25 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['VVL'])
        rule26 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'], cd['EL'])
        rule27 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['VVL'])
        rule28 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['VL'])
        rule29 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'],
                           cd['VVL'])
        rule30 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['VL'])
        rule31 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['VL'])
        rule32 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['VVL'])
        rule33 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['VL'])
        rule34 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['L'])
        rule35 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['VL'])
        rule36 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['L'])
        rule37 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['VVL'])
        rule38 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['EL'])
        rule39 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['VVL'])
        rule40 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['VL'])
        rule41 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['VVL'])
        rule42 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['VL'])
        rule43 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['VL'])
        rule44 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'],
                           cd['VVL'])
        rule45 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['VL'])
        rule46 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['L'])
        rule47 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'], cd['VL'])
        rule48 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['L'])
        rule49 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['L'])
        rule50 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['VL'])
        rule51 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['L'])
        rule52 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['ML'])
        rule53 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['L'])
        rule54 = ctrl.Rule(ap['Mild'] & an['Mild'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['ML'])
        rule55 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['VVL'])
        rule56 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['EL'])
        rule57 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['VVL'])
        rule58 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['VL'])
        rule59 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['VVL'])
        rule60 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['VL'])
        rule61 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['VL'])
        rule62 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'],
                           cd['VVL'])
        rule63 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['VL'])
        rule64 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['L'])
        rule65 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'], cd['VL'])
        rule66 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['L'])
        rule67 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['L'])
        rule68 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['VL'])
        rule69 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['L'])
        rule70 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['ML'])
        rule71 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['L'])
        rule72 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['ML'])
        rule73 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['VL'])
        rule74 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['VVL'])
        rule75 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['VL'])
        rule76 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['L'])
        rule77 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['VL'])
        rule78 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['L'])
        rule79 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['L'])
        rule80 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'], cd['VL'])
        rule81 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['L'])
        rule82 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['ML'])
        rule83 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'], cd['L'])
        rule84 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['ML'])
        rule85 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['ML'])
        rule86 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['L'])
        rule87 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['ML'])
        rule88 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['M'])
        rule89 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['ML'])
        rule90 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['M'])
        rule91 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['L'])
        rule92 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['VL'])
        rule93 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['L'])
        rule94 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['ML'])
        rule95 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['L'])
        rule96 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['ML'])
        rule97 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['ML'])
        rule98 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'], cd['L'])
        rule99 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['ML'])
        rule100 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['M'])
        rule101 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'], cd['ML'])
        rule102 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['M'])
        rule103 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['M'])
        rule104 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['ML'])
        rule105 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['M'])
        rule106 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['MH'])
        rule107 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['M'])
        rule108 = ctrl.Rule(ap['Mild'] & an['Mod'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['MH'])
        rule109 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['L'])
        rule110 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['VL'])
        rule111 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['L'])
        rule112 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['ML'])
        rule113 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['L'])
        rule114 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['ML'])
        rule115 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['ML'])
        rule116 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'], cd['L'])
        rule117 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['ML'])
        rule118 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['M'])
        rule119 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'],
                            cd['ML'])
        rule120 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['M'])
        rule121 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['M'])
        rule122 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['ML'])
        rule123 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['M'])
        rule124 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['MH'])
        rule125 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['M'])
        rule126 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['MH'])
        rule127 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['ML'])
        rule128 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['L'])
        rule129 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['ML'])
        rule130 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['M'])
        rule131 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['ML'])
        rule132 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['M'])
        rule133 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['M'])
        rule134 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'], cd['ML'])
        rule135 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['M'])
        rule136 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['MH'])
        rule137 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'], cd['M'])
        rule138 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['MH'])
        rule139 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['MH'])
        rule140 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['M'])
        rule141 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['MH'])
        rule142 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['H'])
        rule143 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['MH'])
        rule144 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['H'])
        rule145 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['M'])
        rule146 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['ML'])
        rule147 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['M'])
        rule148 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['MH'])
        rule149 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['M'])
        rule150 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['MH'])
        rule151 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['MH'])
        rule152 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'], cd['M'])
        rule153 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['MH'])
        rule154 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['H'])
        rule155 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'], cd['MH'])
        rule156 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['H'])
        rule157 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['VH'])
        rule158 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['H'])
        rule159 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['VH'])
        rule160 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['VVH'])
        rule161 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['VH'])
        rule162 = ctrl.Rule(ap['Mild'] & an['Sev'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['VVH'])
        rule163 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['VVL'])
        rule164 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['EL'])
        rule165 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['VVL'])
        rule166 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['VL'])
        rule167 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['VVL'])
        rule168 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['VL'])
        rule169 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['VL'])
        rule170 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'], cd['VVL'])
        rule171 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['VL'])
        rule172 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['L'])
        rule173 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'], cd['VL'])
        rule174 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['L'])
        rule175 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['L'])
        rule176 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['VL'])
        rule177 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['L'])
        rule178 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['ML'])
        rule179 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['L'])
        rule180 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['ML'])
        rule181 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['VL'])
        rule182 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['VVL'])
        rule183 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['VL'])
        rule184 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['L'])
        rule185 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['VL'])
        rule186 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['L'])
        rule187 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['L'])
        rule188 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'], cd['VL'])
        rule189 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['L'])
        rule190 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['ML'])
        rule191 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'], cd['L'])
        rule192 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['ML'])
        rule193 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['ML'])
        rule194 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['L'])
        rule195 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['ML'])
        rule196 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['M'])
        rule197 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['ML'])
        rule198 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['M'])
        rule199 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['L'])
        rule200 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['VL'])
        rule201 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['L'])
        rule202 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['ML'])
        rule203 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['L'])
        rule204 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['ML'])
        rule205 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['ML'])
        rule206 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'], cd['L'])
        rule207 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['ML'])
        rule208 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['M'])
        rule209 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'], cd['ML'])
        rule210 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['M'])
        rule211 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['M'])
        rule212 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['ML'])
        rule213 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['M'])
        rule214 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['MH'])
        rule215 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['M'])
        rule216 = ctrl.Rule(ap['Mod'] & an['Mild'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['MH'])
        rule217 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['L'])
        rule218 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['VL'])
        rule219 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['L'])
        rule220 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['ML'])
        rule221 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['L'])
        rule222 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['ML'])
        rule223 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['ML'])
        rule224 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'], cd['L'])
        rule225 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['ML'])
        rule226 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['M'])
        rule227 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'], cd['ML'])
        rule228 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['M'])
        rule229 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['M'])
        rule230 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['ML'])
        rule231 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['M'])
        rule232 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['MH'])
        rule233 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['M'])
        rule234 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['MH'])
        rule235 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['ML'])
        rule236 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['L'])
        rule237 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['ML'])
        rule238 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['M'])
        rule239 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['ML'])
        rule240 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['M'])
        rule241 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['M'])
        rule242 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'], cd['ML'])
        rule243 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['M'])
        rule244 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['MH'])
        rule245 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'], cd['M'])
        rule246 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['MH'])
        rule247 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['MH'])
        rule248 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['M'])
        rule249 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['MH'])
        rule250 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['H'])
        rule251 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['MH'])
        rule252 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['H'])
        rule253 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['M'])
        rule254 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['ML'])
        rule255 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['M'])
        rule256 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['MH'])
        rule257 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['M'])
        rule258 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['MH'])
        rule259 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['MH'])
        rule260 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'], cd['M'])
        rule261 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['MH'])
        rule262 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['H'])
        rule263 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'], cd['MH'])
        rule264 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['H'])
        rule265 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['H'])
        rule266 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['MH'])
        rule267 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['H'])
        rule268 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['VH'])
        rule269 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['H'])
        rule270 = ctrl.Rule(ap['Mod'] & an['Mod'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['VH'])
        rule271 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['M'])
        rule272 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['ML'])
        rule273 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['M'])
        rule274 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['MH'])
        rule275 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['M'])
        rule276 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['MH'])
        rule277 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['MH'])
        rule278 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'], cd['M'])
        rule279 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['MH'])
        rule280 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['H'])
        rule281 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'], cd['MH'])
        rule282 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['H'])
        rule283 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['H'])
        rule284 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['MH'])
        rule285 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['H'])
        rule286 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['VH'])
        rule287 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['H'])
        rule288 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['VH'])
        rule289 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['MH'])
        rule290 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['M'])
        rule291 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['MH'])
        rule292 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['H'])
        rule293 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['MH'])
        rule294 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['H'])
        rule295 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['H'])
        rule296 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'], cd['MH'])
        rule297 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['H'])
        rule298 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['VH'])
        rule299 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'], cd['H'])
        rule300 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['VH'])
        rule301 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['VH'])
        rule302 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['H'])
        rule303 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['VH'])
        rule304 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['VVH'])
        rule305 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['VH'])
        rule306 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['VVH'])
        rule307 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['H'])
        rule308 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['MH'])
        rule309 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['H'])
        rule310 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['VH'])
        rule311 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['H'])
        rule312 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['VH'])
        rule313 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['VH'])
        rule314 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'], cd['H'])
        rule315 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['VH'])
        rule316 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['VVH'])
        rule317 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'], cd['VH'])
        rule318 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['VVH'])
        rule319 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['VVH'])
        rule320 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['VH'])
        rule321 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['VVH'])
        rule322 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['VVH'])
        rule323 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['VVH'])
        rule324 = ctrl.Rule(ap['Mod'] & an['Sev'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['VVH'])
        rule325 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['L'])
        rule326 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['VL'])
        rule327 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['L'])
        rule328 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['ML'])
        rule329 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['L'])
        rule330 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['ML'])
        rule331 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['ML'])
        rule332 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'], cd['L'])
        rule333 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['ML'])
        rule334 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['M'])
        rule335 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'],cd['ML'])
        rule336 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['M'])
        rule337 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['M'])
        rule338 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['ML'])
        rule339 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['M'])
        rule340 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['MH'])
        rule341 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['M'])
        rule342 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['MH'])
        rule343 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['ML'])
        rule344 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['L'])
        rule345 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['ML'])
        rule346 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['M'])
        rule347 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['ML'])
        rule348 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['M'])
        rule349 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['M'])
        rule350 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'], cd['ML'])
        rule351 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['M'])
        rule352 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['MH'])
        rule353 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'], cd['M'])
        rule354 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['MH'])
        rule355 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['MH'])
        rule356 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['M'])
        rule357 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['MH'])
        rule358 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['H'])
        rule359 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['MH'])
        rule360 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['H'])
        rule361 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['M'])
        rule362 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['ML'])
        rule363 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['M'])
        rule364 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['MH'])
        rule365 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['M'])
        rule366 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['MH'])
        rule367 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['MH'])
        rule368 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'], cd['M'])
        rule369 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['MH'])
        rule370 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['H'])
        rule371 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'], cd['MH'])
        rule372 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['H'])
        rule373 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['VH'])
        rule374 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['H'])
        rule375 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['VH'])
        rule376 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['VVH'])
        rule377 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['VH'])
        rule378 = ctrl.Rule(ap['Sev'] & an['Mild'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['VVH'])
        rule379 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['M'])
        rule380 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['ML'])
        rule381 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['M'])
        rule382 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['MH'])
        rule383 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['M'])
        rule384 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['MH'])
        rule385 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['MH'])
        rule386 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'], cd['M'])
        rule387 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['MH'])
        rule388 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['H'])
        rule389 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'], cd['MH'])
        rule390 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['H'])
        rule391 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['H'])
        rule392 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['MH'])
        rule393 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['H'])
        rule394 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['VH'])
        rule395 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['H'])
        rule396 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['VH'])
        rule397 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['MH'])
        rule398 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['M'])
        rule399 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['MH'])
        rule400 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['H'])
        rule401 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['MH'])
        rule402 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['H'])
        rule403 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['H'])
        rule404 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'], cd['MH'])
        rule405 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['H'])
        rule406 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['VH'])
        rule407 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'], cd['H'])
        rule408 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['VH'])
        rule409 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['VH'])
        rule410 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['H'])
        rule411 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['VH'])
        rule412 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['VVH'])
        rule413 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['VH'])
        rule414 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['VVH'])
        rule415 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['H'])
        rule416 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['MH'])
        rule417 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['H'])
        rule418 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['VH'])
        rule419 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['H'])
        rule420 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['VH'])
        rule421 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['VH'])
        rule422 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'], cd['H'])
        rule423 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['VH'])
        rule424 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['VVH'])
        rule425 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'], cd['VH'])
        rule426 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['VVH'])
        rule427 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['VVH'])
        rule428 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['VH'])
        rule429 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['VVH'])
        rule430 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['VVH'])
        rule431 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['VVH'])
        rule432 = ctrl.Rule(ap['Sev'] & an['Mod'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['VVH'])
        rule433 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['H'])
        rule434 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['MH'])
        rule435 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mild'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['H'])
        rule436 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['VH'])
        rule437 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['H'])
        rule438 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mild'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['VH'])
        rule439 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['VH'])
        rule440 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'], cd['H'])
        rule441 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mild'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['VH'])
        rule442 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['VVH'])
        rule443 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'], cd['VH'])
        rule444 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mild'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['VVH'])
        rule445 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['VH'])
        rule446 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['H'])
        rule447 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mild'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['VH'])
        rule448 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['VVH'])
        rule449 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['VH'])
        rule450 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mild'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['VVH'])
        rule451 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['VH'])
        rule452 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['H'])
        rule453 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mod'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['VH'])
        rule454 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['VVH'])
        rule455 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['VH'])
        rule456 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mod'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['VVH'])
        rule457 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['VVH'])
        rule458 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'], cd['VH'])
        rule459 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mod'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['VVH'])
        rule460 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['VVH'])
        rule461 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'], cd['VVH'])
        rule462 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mod'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['VVH'])
        rule463 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['VVH'])
        rule464 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['VVH'])
        rule465 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mod'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['VVH'])
        rule466 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['VVH'])
        rule467 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['VVH'])
        rule468 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Mod'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['VVH'])
        rule469 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['UW'], cd['VVH'])
        rule470 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['Normal'], cd['VH'])
        rule471 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Sev'] & vom['OnceWeek'] & wl['US'] & bmi['OW'], cd['VVH'])
        rule472 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['UW'], cd['VVH'])
        rule473 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['Normal'], cd['VVH'])
        rule474 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Sev'] & vom['OnceWeek'] & wl['UL'] & bmi['OW'], cd['VVH'])
        rule475 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['UW'], cd['VVH'])
        rule476 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['Normal'], cd['VVH'])
        rule477 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Sev'] & vom['ThriceWeek'] & wl['US'] & bmi['OW'], cd['VVH'])
        rule478 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['UW'], cd['VVH'])
        rule479 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['Normal'], cd['VVH'])
        rule480 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Sev'] & vom['ThriceWeek'] & wl['UL'] & bmi['OW'], cd['VVH'])
        rule481 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['UW'], cd['VVH'])
        rule482 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['Normal'], cd['VVH'])
        rule483 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Sev'] & vom['Daily'] & wl['US'] & bmi['OW'], cd['VVH'])
        rule484 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['UW'], cd['VVH'])
        rule485 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['Normal'], cd['VVH'])
        rule486 = ctrl.Rule(ap['Sev'] & an['Sev'] & da['Sev'] & vom['Daily'] & wl['UL'] & bmi['OW'], cd['VVH'])
        rule = []
        for i in range(1, 487):
            rule.append(eval("rule" + str(i)))
        cdlevel = ctrl.ControlSystemSimulation(fuzz.control.ControlSystem(rule))
        cdlevel.input['ap'] = Abdominal_Pain_value
        cdlevel.input['an'] = Anemia_value
        cdlevel.input['da'] = Diarrhea_value
        cdlevel.input['vom'] = Vomiting_value
        cdlevel.input['wl'] = Weight_Loss_value
        cdlevel.input['bmi'] = BMI_value
        cdlevel.compute()

        return(str(cdlevel.output['cd']))
        
        
# Symptoms_input()
# Calculate()